### PR TITLE
Compatibility fix for users with FontAwesome 5 JS SVG enabled

### PR DESCRIPTION
**Pull request by samanthajean**
Added the new .fab class to the .sbi_follow_btn icon tag and resolved some styling issues with the right margins of the new svg.fa-instagram version of the icon.

### CODE REVIEW

**Comment by craigschlegel** [comment]
Hey Samantha!

Thanks for this. We have plans to use SVG icons instead of fonts in a near future update as well. I hope you're having a great week!

**Comment by samanthajean** [comment]
Thank you for merging my update! I considered just updating the Font Awesome version altogether, but thought that might be a little overboard and could cause more compatibility issues with the numerous people still on the older version of Font Awesome. Love your plugin! I've used it on several of the sites I've built.

**Comment by craigschlegel** [comment]
Glad you like the plugin! And that's a good question (we actually have only had a handful of contributors). I suppose you could delete it since it's in the master branch now. 

Just to double check, was the only change you made in the CSS file this? 

#sb_instagram #sbi_load .sbi_follow_btn svg.fa-instagram{
margin-right: 7px;
}

For some reason github was showing the whole file being changed even though it looked like it was just these few lines. 

Thanks again!

**Comment by samanthajean** [comment]
Yeah that was it. I don't know why it was showing the entire file being changed. It did that in the diff check too, but I wasn't sure how to resolve it. I thought it may have just had issues parsing CSS because it didn't seem to have any issues with any PHP or HTML I have checked in the past. 

If you have any suggestions, I would be open to them!

**Comment by craigschlegel** [comment]
I have no idea either actually. If I find out I will let you know!

**Pull request merged**
